// Mocks generated by Mockito 5.4.6 from annotations
// in dogfydiet_app/test/application/screens/user/profile_screen/profile_screen_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dogfydiet_app/domain/model/objects/order.dart' as _i4;
import 'package:dogfydiet_app/domain/services/order_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OrderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderService extends _i1.Mock implements _i2.OrderService {
  MockOrderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Order>> getAllOrders() => (super.noSuchMethod(
        Invocation.method(
          #getAllOrders,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Order>>.value(<_i4.Order>[]),
      ) as _i3.Future<List<_i4.Order>>);

  @override
  _i3.Future<_i4.Order?> getOrderById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getOrderById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Order?>.value(),
      ) as _i3.Future<_i4.Order?>);
}
