name: dogfydiet_app
description: "Dogfy Diet: Natural cooked food for dogs"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  equatable: ^2.0.7
  go_router: ^16.0.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  hive_ce_generator: ^1.9.2
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/common/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/common/dd_foreground.png
  ios_image_path: assets/images/common/dogfy_diet_ios_logo.jpg
  adaptive_icon_background: "#ED6948"
  adaptive_icon_foreground: assets/images/common/dd_foreground.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ED6948"
  image: assets/images/common/dogfy_diet_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

android_12:
  color: "#ED6948"
  icon_background_color: "#ED6948"
  image: assets/images/common/dogfy_diet_logo.png
  branding: null
  icon_background: null