// Mocks generated by Mockito 5.4.6 from annotations
// in dogfydiet_app/test/application/screens/splash_screen/splash_screen_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dogfydiet_app/domain/services/core/router_service.dart' as _i3;
import 'package:dogfydiet_app/domain/services/subscription_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubscriptionService_0 extends _i1.SmartFake
    implements _i2.SubscriptionService {
  _FakeSubscriptionService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RouterService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouterService extends _i1.Mock implements _i3.RouterService {
  MockRouterService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SubscriptionService get subscriptionService => (super.noSuchMethod(
        Invocation.getter(#subscriptionService),
        returnValue: _FakeSubscriptionService_0(
          this,
          Invocation.getter(#subscriptionService),
        ),
      ) as _i2.SubscriptionService);

  @override
  _i4.Future<String> getNextPage() => (super.noSuchMethod(
        Invocation.method(
          #getNextPage,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #getNextPage,
            [],
          ),
        )),
      ) as _i4.Future<String>);
}
